### ISSUE TITLE
API Error: A.map is not a function

### ISSUE THREAD

**Issue by cexll** [musistudio/claude-code-router#23]
is wrong ? 

```bash
/init
...
⎿  API Error: A.map is not a function
```

**Comment by musistudio** [comment]
Yes, it looks like some tool execution requests are throwing errors, but not every time, and it doesn’t seem to affect the tool execution. I’m currently looking into the specific logic in claude code to fix the error.

**Comment by cexll** [comment]
ya, i use deepseek-chat , ccr code  then run /init trigger API Error: A.map it not a function 
thanks you fix this issue

**Comment by ysm-dev** [comment]
is this fixed on latest version?

**Comment by musistudio** [comment]
> is this fixed on latest version?

fixed in v1.0.8

**Comment by ysm-dev** [comment]
@musistudio 
it still happens in v1.0.8

<img width="433" alt="Image" src="https://github.com/user-attachments/assets/7e263f1e-7970-4866-be09-ed0d392dc906" />

**Comment by musistudio** [comment]
> [@musistudio](https://github.com/musistudio) it still happens in v1.0.8
> 
> <img alt="Image" width="433" src="https://private-user-images.githubusercontent.com/18487241/455823508-7e263f1e-7970-4866-be09-ed0d392dc906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAxMzgzMzgsIm5iZiI6MTc1MDEzODAzOCwicGF0aCI6Ii8xODQ4NzI0MS80NTU4MjM1MDgtN2UyNjNmMWUtNzk3MC00ODY2LWJlMDktZWQwZDM5MmRjOTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjE3VDA1MjcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzMxZjk5ODI0NzczNjYwYzJmM2NkOWRiYjQzZDFlNTY3NGUyNjYzMjIxM2I1ZGRkZDNmODkyNWNkNzVmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Brvkmv7Li2YVaMYGqN0vYNwthddbOi7hLBHIsfzmOi8">

That looks like a response from the LLM. Try using `/clear` command to reset the context.

**Comment by ysm-dev** [comment]
@musistudio I don't have any context, I'm using https://github.com/anthropics/claude-code-action and it happens inside of github actions

**Comment by mountainwitchx** [comment]
I got the same error this morning with Gemma 27b, think it was related to context size though. I switched to Devstral with a much larger context size and everything worked. 

I ran Claude Code through Burp to check and the system prompt + tool doc strings. System prompt is about 3,000 tokens, then tool specs (on plan mode) was about 6,000+. So it's approaching 9-10k context window before you even load any of your context in..

**Comment by yxl23** [comment]
我也是这个问题

![Image](https://github.com/user-attachments/assets/46cb40ed-c327-48c3-a252-a346ed054e4e)

**Comment by musistudio** [comment]
> [@musistudio](https://github.com/musistudio) I don't have any context, I'm using https://github.com/anthropics/claude-code-action and it happens inside of github actions

That sounds really interesting and I’ve forked their repository and am working on creating a claude-code-router-action.

**Comment by musistudio** [comment]
> 我也是这个问题
> 
> ![Image](https://github.com/user-attachments/assets/46cb40ed-c327-48c3-a252-a346ed054e4e)

你的claude-code-router版本是多少？可以使用`ccr -v`查看

**Comment by yxl23** [comment]
claude-code-router version: 1.0.7

**Comment by yxl23** [comment]
我要执行什么命令来升级呢

**Comment by ysm-dev** [comment]
> > [@musistudio](https://github.com/musistudio) I don't have any context, I'm using [anthropics/claude-code-action](https://github.com/anthropics/claude-code-action?rgh-link-date=2025-06-17T13%3A34%3A44.000Z) and it happens inside of github actions
> 
> That sounds really interesting and I’ve forked their repository and am working on creating a claude-code-router-action.

I'm using like this:

```yml
      - name: Setup Claude Code Router config
        run: |
          mkdir -p $HOME/.claude-code-router
          cat << 'EOF' > $HOME/.claude-code-router/config.json
          {
            "log": true,
            "OPENAI_API_KEY": "random",
            "OPENAI_BASE_URL": "http://localhost:6229",
            "OPENAI_MODEL": "claude-sonnet-4"
          }
          EOF

      - name: Start Claude Code Router
        run: |
          nohup bunx @musistudio/claude-code-router@1.0.8 start &
        shell: bash

      - uses: anthropics/claude-code-action@beta
        env:
          ANTHROPIC_BASE_URL: http://localhost:3456
```
